Fix/rename plugin and fix port
taPublic/zsh-dev-tools pull request #6
Opened 2019-06-18 19:06 UTC by Aleserche

2019-06-18 19:56 UTC, TorinAsakura requested changes

2019-06-18 19:56 UTC, TorinAsakura commented on zsh-theia-dev-tools.plugin.zsh
> +    echo "$(docker inspect --format='{{(index (index .NetworkSettings.Ports "3000/tcp") 0).HostPort}}' au-backend-skeleton-ide)"
это что за херня? Зачем тут это?

2019-06-18 20:11 UTC, Aleserche commented on zsh-theia-dev-tools.plugin.zsh
> +    echo "$(docker inspect --format='{{(index (index .NetworkSettings.Ports "3000/tcp") 0).HostPort}}' au-backend-skeleton-ide)"
Если ide запущена, отдать порт запущенной. Тогда при повторном старте кинет в правильное место.

2019-06-19 07:09 UTC, TorinAsakura approved these changes

2019-06-19 07:10 UTC, merged